font_size 10.0
font_family JetBrains Mono
window_margin_width 4
window_margin_height 4
background_opacity 0.8
scrollback_indicator_opacity 0

map ctrl+l combine : clear_terminal clear active : send_text normal,application \x0c

# BEGIN_KITTY_THEME
# My-Theme
include current-theme.conf
# END_KITTY_THEME
